# Generated by Django 5.0.6 on 2024-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('genres', models.CharField(max_length=200, null=True)),
                ('original_language', models.CharField(max_length=2, null=True)),
                ('overview', models.CharField(max_length=1000, null=True)),
                ('popularity', models.FloatField(null=True)),
                ('production_companies', models.CharField(max_length=700, null=True)),
                ('release_date', models.CharField(max_length=20, null=True)),
                ('budget', models.FloatField(null=True)),
                ('revenue', models.FloatField(null=True)),
                ('runtime', models.FloatField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('tagline', models.CharField(max_length=300, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.FloatField(null=True)),
                ('credits', models.CharField(max_length=7200, null=True)),
                ('keywords', models.CharField(max_length=1300, null=True)),
                ('poster_path', models.CharField(max_length=32, null=True)),
                ('backdrop_path', models.CharField(max_length=32, null=True)),
                ('recommendations', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
