# Generated by Django 5.0.6 on 2024-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0002_alter_film_release_date_guardati'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardati',
            name='voto',
            field=models.FloatField(null=True),
        ),
    ]
