# Generated by Django 5.0.6 on 2024-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0004_daguardare'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
