# Generated by Django 5.0.6 on 2024-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova', '0005_film_poster_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='credits',
            field=models.CharField(blank=True, max_length=7200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='keywords',
            field=models.CharField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='overview',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_path',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='production_companies',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='recommendations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vote_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardati',
            name='voto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
